runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup_java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Cache local Maven repository
      uses: actions/cache@v4.0.2
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
    - name: Cache Sonarcloud packages
      uses: actions/cache@v4.0.2
      with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar